"""20220307_add_finished_at_column

Revision ID: 9e0ada5cd216
Revises: 6528c9fc31f8
Create Date: 2022-03-07 17:33:21.746781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e0ada5cd216'
down_revision = '6528c9fc31f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'finished_at')
    # ### end Alembic commands ###
